# Generated by Django 3.1.4 on 2021-01-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apabout', models.TextField()),
                ('aboutMinister', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='tplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('history', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='video/')),
                ('vdate', models.DateField()),
            ],
        ),
    ]
