# Generated by Django 3.1.4 on 2021-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutap',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
