# Generated by Django 3.1.4 on 2021-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0002_auto_20210115_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutap',
            name='image',
            field=models.ImageField(upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='tplace',
            name='image',
            field=models.FileField(upload_to='images/%y'),
        ),
        migrations.AlterField(
            model_name='tplace',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
