# Generated by Django 3.1.4 on 2021-01-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0003_auto_20210115_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutap',
            name='image',
        ),
        migrations.AlterField(
            model_name='tplace',
            name='image',
            field=models.ImageField(upload_to='images/%y'),
        ),
    ]
