# Generated by Django 3.1.4 on 2021-01-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0004_auto_20210115_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='place1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='place1images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='place1video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('vdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='tplace',
        ),
        migrations.AlterField(
            model_name='aboutimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
