# Generated by Django 3.1.4 on 2021-01-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0005_auto_20210115_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1images',
            old_name='image',
            new_name='img1',
        ),
    ]
