# Generated by Django 3.1.4 on 2021-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristplaces', '0006_auto_20210119_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='place2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='place2images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='place2video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('vdate', models.DateField()),
            ],
        ),
    ]
